---
title: "Data-Manipulation-Excersie1"
output: html_document
---

Load the data in RStudio:

df.refine_original <- read_csv("/Users/genuswilson/Desktop/refine_original.csv")

Clean up brand names:

f.refine_original$company[df.refine_original$company=="phillipS"] <- "phillips"
df.refine_original$company[df.refine_original$company=="fillips"] <- "phillips"
df.refine_original$company[df.refine_original$company=="phlips"] <- "phillips"
df.refine_original$company[df.refine_original$company=="phllips"] <- "phillips"
df.refine_original$company[df.refine_original$company=="philips"] <- "phillips"
df.refine_original$company[df.refine_original$company=="Phillips"] <- "phillips"
df.refine_original$company[df.refine_original$company=="phillps"] <- "phillips"

df.refine_original$company[df.refine_original$company=="Akzo"] <- "akzo"
df.refine_original$company[df.refine_original$company=="AKZO"] <- "akzo"
df.refine_original$company[df.refine_original$company=="akz0"] <- "akzo"
df.refine_original$company[df.refine_original$company=="ak zo"] <- "akzo"

df.refine_original$company[df.refine_original$company=="Van Houten"] <- "van houten"
df.refine_original$company[df.refine_original$company=="van Houten"] <- "van houten"
df.refine_original$company[df.refine_original$company=="Van Houten"] <- "van houten"

df.refine_original$company[df.refine_original$company=="unilver"] <- "unilever"
df.refine_original$company[df.refine_original$company=="Unilever"] <- "unilever"

Separate product code and number:

df.refine_original <- df.refine_original %>% separate( "Product code / number", into=c("product_code", "Product_number"), sep = "-")

Add product categories:

df.refine_original$product_category <- ifelse(df.refine_original$product_code == "p", "Smartphone",
        ifelse(df.refine_original$product_code == "v", "TV",
        ifelse(df.refine_original$product_code == "x", "Laptop","Tablet")))

Add full address for geocoding:

df.refine_original <- unite(df.refine_original, full_address, c(address,city,country), sep = ",")

Create dummy variables for company and product category:

df.refine_original <- df.refine_original %>% mutate(company_philips = ifelse(company =="philips", 1, 0)) %>%
           mutate(company_akzo = ifelse(company == "akzo", 1, 0)) %>%
           mutate(company_van_houten = ifelse(company == "van_houten", 1, 0)) %>%
           mutate(company_unilever = ifelse(company == "unilever", 1, 0))

df.refine_original<- df.refine_original %>% mutate(product_smartphone = ifelse(product_category == "Smartphone", 1, 0)) %>%
  mutate(product_TV = ifelse(product_category == "TV", 1, 0)) %>%
  mutate(product_laptop = ifelse(product_category == "Laptop", 1, 0)) %>%
  mutate(product_tablet = ifelse(product_category == "Tablet", 1, 0))

New data:

write.csv(df.refine_original, file = "refine_clean.csv")









